# -*- coding: utf-8 -*-
from django.conf.urls.defaults import *

urlpatterns = patterns('',
    (r'^$', 'selfpublish.views.home', {}, "selfpublish_home"),
    (r'^themes/$', 'selfpublish.views.theme_browse',),
    (r'^theme/(?P<id>[-\d]+)/$', 'selfpublish.views.theme_detail',),
    (r'^theme/(?P<id>[-\d]+)/select/$', 'selfpublish.views.theme_select_membership',),
    (r'^theme/(?P<id>[-\d]+)/compare-book-sizes/$', 'selfpublish.views.pagecount_compare',),
    (r'^publication/setup/(?P<setup_key>[-\w]+)/$', 'selfpublish.views.publication_setup',),
    (r'^publication/(?P<id>[-\d]+)/$', 'selfpublish.views.publication_detail',),
    (r'^publication/(?P<publication_id>[-\d]+)/sales/$', 'selfpublish.views.sales_home',),
    (r'^publication/(?P<publication_id>[-\d]+)/sales/leads/$', 'selfpublish.views.lead_list',),
    (r'^publication/(?P<publication_id>[-\d]+)/sales/leads/import/$', 'selfpublish.views.lead_import',),
    (r'^publication/(?P<publication_id>[-\d]+)/sales/lead/add/$', 'selfpublish.views.lead_add',),
    (r'^publication/(?P<publication_id>[-\d]+)/sales/lead/(?P<lead_id>[-\d]+)/invite/$', 'selfpublish.views.lead_invite_send',),
    (r'^publication/(?P<publication_id>[-\d]+)/sales/lead/(?P<lead_id>[-\d]+)/$', 'selfpublish.views.lead_detail',),
    (r'^publication/(?P<publication_id>[-\d]+)/layout/(?P<layout_id>[-\d]+)/$', 'selfpublish.views.layout_detail',),
    (r'^publication/(?P<publication_id>[-\d]+)/layout/(?P<layout_id>[-\d]+)/change-layout/$', 'selfpublish.views.change_layout',),
    (r'^publication/(?P<publication_id>[-\d]+)/layout/(?P<layout_id>[-\d]+)/change-layout/confirm/$', 'selfpublish.views.change_layout_execute',),
    (r'^publication/(?P<publication_id>[-\d]+)/layout/(?P<layout_id>[-\d]+)/block/(?P<block_id>[-\d]+)/$', 'selfpublish.views.block_detail',),
    (r'^publication/(?P<publication_id>[-\d]+)/layout/(?P<layout_id>[-\d]+)/block/(?P<block_id>[-\d]+)/select/$', 'selfpublish.views.media_select',),
    (r'^sponsor/invite/(?P<invitation_code>[-\w]+)/$', 'selfpublish.views.lead_invite_accept',),
    (r'^sponsor/(?P<publication_id>[-\d]+)/$', 'selfpublish.views.sponsor_welcome',),
    (r'^sponsor/(?P<publication_id>[-\d]+)/premium/$', 'selfpublish.views.sponsor_display',),
    (r'^sponsor/(?P<publication_id>[-\d]+)/premium/reserve/(?P<adblock_id>[-\d]+)/$', 'selfpublish.views.reserve_display',),
    (r'^sponsor/(?P<publication_id>[-\d]+)/premium/(?P<displayad_id>[-\d]+)/$', 'selfpublish.views.displayad_detail',),
    (r'^sponsor/(?P<publication_id>[-\d]+)/business-listings/$', 'selfpublish.views.sponsor_listings',),
    (r'^sponsor/(?P<publication_id>[-\d]+)/business-listings/reserve/$', 'selfpublish.views.reserve_listing',),
    (r'^sponsor/(?P<publication_id>[-\d]+)/business-listing/(?P<linead_id>[-\d]+)/$', 'selfpublish.views.linead_detail',),
    (r'^sponsor/(?P<publication_id>[-\d]+)/contact/$', 'selfpublish.views.sponsor_contact',),
    (r'^listing/setup/(?P<setup_key>[-\w]+)/$', 'selfpublish.views.linead_setup', {}, "listing_setup"),
    (r'^premium/setup/(?P<setup_key>[-\w]+)/$', 'selfpublish.views.displayad_setup', {}, "displayad_setup"),

)
